### ISSUE TITLE
truncate boilerplate strings in drop-down menus, because they are too long

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/message-manager#145]
...which is potentially breaking layout (in FMB this comes up in a popup).

Simplest solution: add ellipsis in the middle of long strings, which would work for now.
(Otherwise, display the text in a div which can word-wrap... but that's practically what the text-area does anyway -- so ambiguous strings can still be found if the ellipsis is making them appear the same in the menu)

**Comment by dracos** [comment]
There is a way for a select to be width constrained more than its contents, would that work?

**Comment by davewhiteland** [comment]
Yes definitely, this is just about layout :-)

**Comment by davewhiteland** [comment]
Closed in mysociety/fixmystreet@e4c65814e77d
