### ISSUE TITLE
stop using .htaccess-DEPLOY or else document it

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/message-manager#15]
.htaccess in webroot should probably be included by default (as Cake wants)?
Need to decide the right way of doing this -- easiest in our deployment if there isn't a .htaccess in the repo here.

**Comment by dracos** [comment]
Our deployment doesn't care if there's an htaccess or not, e.g. our Wordpress sites all have one.

**Comment by davewhiteland** [comment]
.htaccess moved into the right place, with the fastCGI tweak included in it.
