### ISSUE TITLE
make incoming messages on SMS gateway hit the MM URL

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/message-manager#16]
This issue is now about configuring the SMS gateway to hit the MM URL -- specifically, although the gateway can't use login credentials, it could trigger a webservice on the local (gateway) server which could, if we thought it was worth it. Otherwise, we need to consider IP restriction for incoming messages.

See also #19 which is about enabling the incoming message code on the MM (i.e., accepting the specific URL format which InfoTxt will use).

**Comment by BenJam** [comment]
this is more than a little security risk.

**Comment by davewhiteland** [comment]
Ah, the security issues relate to the original infoTxt gateway which couldn't handle explicit login credentials; not sure of current SMS gateway's capabilities, but this won't be an issue if it can (MM supports basic htauth, which would be fine over https).

**Comment by davewhiteland** [comment]
This no longer applies because we're using the Netcast gateway which does not make requests with incoming messages. Instead we must poll to pull them in at our convenience. This work is covered by issue #19.
