### ISSUE TITLE
run FMB over https only, redirecting URLs to same-URL with https protocol

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/message-manager#170]
Currently we're running FMB over http _and_ https
- staff accounts ought to be logging in over https
- we want to offer /admin access which really should be over https
- MessageManager _must_ know which protocol users will be accessing it from, because it only supports one CORS_ALLOWED URL -- see #106 
- _important_ publicity will be advertising the `http:` URL which is why it's essential that redirection to http happens nicely (i.e., public users might not even notice the redirection)

**Comment by davewhiteland** [comment]
Note we also have to ensure we can pull OSM maps via a secure url for this to prevent scary warnings on some browsers concerning mixed secure/insecure content warnings.

**Comment by struan** [comment]
Just for reference we did this on Bromley FMS by proxing all the map tile requests through the host serving up the Bromley FMS site.

**Comment by Flupsy** [comment]
@davewhiteland this is done like this:

`RewriteRule /mapit/(.*) http://mapit.mysociety.org/$1 [P,L]
ProxyPassReverse /mapit/ http://mapit.mysociety.org/`

Can you make your mapit calls look like `https://www.fixmybarangay.com/mapit/...`?

**Comment by davewhiteland** [comment]
Yup @struan I think the difference here is -- unlike Bromley -- we're not yet caching the tiles ourselves (Bromley has the tree layer added). Although interestingly it's possible this might be happening in the future because recently Cebu 's DPS has added have a streetlight layer in OSM that it might be nice to render -- but it's certainly not currently the case.

For the pilot caching might not be a big deal cos it's a relatively small area... but for now it might be easier just to reverseproxy the OSM call as Ian suggests.

**Comment by struan** [comment]
That's what I meant.

**Comment by Flupsy** [comment]
I've made it so that

 https://www.fixmybarangay.com/osm/blahblahblah

will be proxied internally to

 http://tile.openstreetmap.org/blahblahblah

I've deployed and tested this and it seems to work.
