### ISSUE TITLE
When a report generated from an SMS is created in FMS it should update the text in MM with the FMS report id

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/message-manager#34]

**Comment by davewhiteland** [comment]
Done this by storing external_source (MM URL) and external_source_id (MM message ID) in the FMS problem table, so we can include it in the display view (actually in the head, conditionally) of the problem report. This in turn allows the client to call (js) message_manager.assign_fms_id(msg_id, fms_id) to notify the MM that FMS has indeed assigned the ID.

This has two main weaknesses:
- it assumes the response page (display) loads OK (and also that the js call goes off OK; I've seen a few intermittent x-domain rejects even though we've got CORS working most of the time), which seems an acceptable risk; 
- it also assumes that the message text was indeed used: this is moot as we're not tracking to see if the text that is auto-inserted is indeed used in the body of the report (the user _could_ edit it so it's no longer the case)
