### ISSUE TITLE
show message threads (replies/responses) in FMB

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/message-manager#41]
Currently we're only showing problem reports and incoming messages in FMS. But for a logged-in Barangay user who is authorised to send replies, it seems necessary to indicate when a message has already been replied to, to prevent this or another user sending duplicate replies. 

This probably means that the MM API for /messages/available will need to return a nested list of replies rather than a simple array, and the FMS display can maybe display them or collapse them.

See issue #40 for the construction of these threads in MM.

**Comment by paullenz** [comment]
Question - is this absolutely essential or a nice to have? (ditto earlier
ticket)

System will work without threading?

**Comment by davewhiteland** [comment]
Yes, essential.

We're providing a means for a barangay staff user to reply to a message (anticipated use: asking for clarification). Without threading, the answer to that message will arrive in MM without any context as a new message, this time without a tag, which means that none of the barangay staff will ever be able to see it (because normal staff accounts will have a Barangay tag to filter out messages that don't have the tag). 

Disregarding threading, it's important that the FMS interface indicates if a message has already been replied to, otherwise different staff may reply multiple times because they have no way of knowing if someone else already has. Since determining if a message has been replied to is a very similar database lookup to pulling the messages anyway (searching for "reply" activity on the message), it seems that returning the messages as list of threads (most presumably of length 1, i.e., no replies) is part of the same problem since a list > 1 implies it has been replied to; it's then up to us how much of that data we display.

**Comment by davewhiteland** [comment]
Now implemented in MM dummy client, which uses identical message_manager_client.js (I pulled in the (small) changes that were made to that file in FMB), so this is very nearly closed! Just needs to be dropped into FMB and tested.

**Comment by davewhiteland** [comment]
Running in FMB now e.g. /mysociety/fixmystreet/commit/34f4806
