### ISSUE TITLE
update templates so all text is appropriate for FixMyBarangay

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/message-manager#42]
Remove "FixMyStreet".

Remove text which is currently aimed at public users, since (for the pilot) only logged in (i.e. staff) users have access to much of the interaction.

**Comment by BenJam** [comment]
Ensure that help template is amended so taht it is applicable to FMB not FMS which includes user access for reporting. Which isn't supported in FMB

**Comment by struan** [comment]
created a translation to change council -> barangay plus some other template changes.
