### ISSUE TITLE
Use Case Documentation (User Stories)

### ISSUE THREAD

**Issue by BenJam** [mysociety/message-manager#44]
In order to ensure @Jedidiah and everyone else understands the user experience.

**Comment by davewhiteland** [comment]
FMB stories have been done: keeping this ticket open for now as there presumably could usefully be stories for MM and FMS-endpoint too?

**Comment by BenJam** [comment]
can we close then reopen if necessary ?

**Comment by davewhiteland** [comment]
Closed since the FMB user stories were emailed -- could reopen if we want MM and FMS to be included.
