### ISSUE TITLE
preload reply text input box with "FixMyBarangay:"

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/message-manager#52]
It's possibly not obvious to the recipient of a reply that's it come from FMB -- preloading the input box with FixMyBarangay: might help

**Comment by BenJam** [comment]
if the SMS service's ability to send messages from Alphanumeric senders is not available.

**Comment by davewhiteland** [comment]
This is now easy for admins to add, since this is now just a boilerplate string.
