### ISSUE TITLE
message manager tab in FMB fails to load in IE

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/message-manager#89]
Something's breaking the js in FMB when trying to display the MM tab in IE (not sure of browser version number, since this was in a demo).

_Might_ be a syntax error, otherwise check btoa as in
https://github.com/mysociety/message-manager/blob/master/app/webroot/js/message_manager_client.js#L98

This may be in the message_manager_client.js (which is -- for as long as this is possible -- identical to the one in the MM repo), so I've tagged it with MM too, and when fixed, make sure to carry the changes into there too.

**Comment by davewhiteland** [comment]
now using safe base64 encoding, that is, this is no longer a Javascript problem: it's IE's security policy not allowing the CORS calls to work -- tested in IE8 by allowing x-domain data in the Internet Options -> Security -> Settings -> Misc -> x-domain enabled, which did _not_ allow the calls.

**Comment by dracos** [comment]
How are you doing CORS? CORS in IE8 needs an extra jQuery plugin in order to work at all, if you haven't already got it.

**Comment by davewhiteland** [comment]
removed priority: since this is no longer erroring on IE, and the target staff for this feature are using FF/Chrome, no longer regarding this as bug (maybe reopen later if this requirement changes)
